services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - uploads:/home/uploads
      - processed:/home/processed
      - daemon:/home/daemonbuilds
  redis:
    image: "redis:latest"
  mongo:
    image: "mongo:latest"
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
volumes:
  uploads:
  processed:
  daemon: