services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
  redis:
    image: "redis:latest"
  mongo:
    image: "mongo:latest"
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
volumes:
  uploads: